Bump

diff --git a/.github/workflows/semver.yml b/.github/workflows/semver.yml
--- a/.github/workflows/semver.yml
+++ b/.github/workflows/semver.yml
@@ -28,7 +28,7 @@ jobs:
         working-directory: ./${{ matrix.crate }}
         run: |
           eval "local_version=$(grep -e '^version = .*$' Cargo.toml | cut -d ' ' -f 3)"
-          eval "target_version=$(cargo semver --api-guidelines --all-features --compact)"
-          echo "Local Version: $local_version\nTarget Version: $target_version"
-          (test "$(printf '%s\n%s\n' "$local_version" "$target_version" | sort -V | head -n 1)" == "$local_version") || \
-            (echo "Need to update $local_version -> $target_version" && exit 1)
+          eval "minimum_required_version=$(cargo semver --api-guidelines --all-features --compact)"
+          printf "Local Version: %s\Minimum Required Version: %s\n" "$local_version" "$minimum_required_version"
+          (test "$(printf '%s\n%s\n' "$local_version" "$minimum_required_version" | sort -V | head -n 1)" == "$minimum_required_version") || \
+            (echo "Need to update $local_version -> $minimum_required_version" && exit 1)
